# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('finger_right_thumb', models.ImageField(blank=True, null=True, upload_to='')),
                ('finger_right_index', models.ImageField(blank=True, null=True, upload_to='')),
                ('finger_right_middle', models.ImageField(blank=True, null=True, upload_to='')),
                ('finger_right_ring', models.ImageField(blank=True, null=True, upload_to='')),
                ('finger_right_little', models.ImageField(blank=True, null=True, upload_to='')),
                ('finger_left_thumb', models.ImageField(blank=True, null=True, upload_to='')),
                ('finger_left_index', models.ImageField(blank=True, null=True, upload_to='')),
                ('finger_left_middle', models.ImageField(blank=True, null=True, upload_to='')),
                ('finger_left_ring', models.ImageField(blank=True, null=True, upload_to='')),
                ('finger_left_little', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
